# Cau hinh server
server.port=${SERVER_PORT:80}

# Thong tin ket noi MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hutech_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Tanluc123}

# Cau hinh Hibernate tu dong tao bang
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true